# Generated by Django 5.2.8 on 2026-02-26 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_target_promoter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_promoter',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_promoters',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
