# Generated by Django 5.2.8 on 2026-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleentry',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
