# Generated by Django 5.2.8 on 2026-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleentry_approved_at_saleentry_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleentry',
            name='bill_no',
            field=models.CharField(default='TEMP', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
