# Generated by Django 5.2.8 on 2026-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_saleentry_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleentry',
            name='model_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleentry',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
